CREATE DATABASE IF NOT EXISTS calculator_db;

USE calculator_db;

CREATE TABLE IF NOT EXISTS calc_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    expression VARCHAR(255),
    result VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
